# Generated by Django 5.0.7 on 2024-08-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('persons', models.IntegerField()),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('steps', models.TextField(blank=True, null=True)),
                ('tips', models.TextField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('nutrients_person', models.FloatField(blank=True, default=0.0, null=True)),
                ('nutrients_table', models.TextField(blank=True, null=True)),
                ('expected_time_total', models.FloatField(blank=True, default=0.0, null=True)),
                ('expected_time_work', models.FloatField(blank=True, default=0.0, null=True)),
                ('expected_time_bake', models.FloatField(blank=True, default=0.0, null=True)),
                ('expected_time_rest', models.FloatField(blank=True, default=0.0, null=True)),
                ('difficulty', models.IntegerField(blank=True, default=0, null=True)),
                ('image_meal', models.ImageField(blank=True, upload_to='recipes')),
                ('rating', models.FloatField(blank=True, default=0.0)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
