# Generated by Django 5.0.7 on 2025-05-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='reference_link',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='video_meal',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
